#!/bin/bash

#SBATCH -J sd_diffusion_MNIST
#SBATCH -p gpu
#SBATCH -A r01273
#SBATCH -o %j_output.txt
#SBATCH -e %j_errors.err
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jctanner@iu.edu
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --gpus-per-node=4
#SBATCH --time=0-12:00:00



#Load any modules that your program needs
module load python/gpu/3.11.5
module load cudatoolkit/12.2
#Run your program
srun python sd/train_diffusion.py